export type LanguageOption = {
  id: string;
  label: string;
  category: string;
  description: string;
  extension: string;
  monacoLanguage: string;
  runnable: boolean;
  runtime?: string;
  runtimeLabel?: string;
  template: string;
  version?: string;
};

const runnableLanguages: LanguageOption[] = [
  {
    id: "javascript",
    label: "JavaScript",
    category: "Web",
    description: "Fast scripting for modern web apps and tooling.",
    extension: "js",
    monacoLanguage: "javascript",
    runnable: true,
    runtime: "javascript",
    runtimeLabel: "Node.js runtime",
    version: "*",
    template: 'console.log("Welcome to VoidLAB");\n',
  },
  {
    id: "typescript",
    label: "TypeScript",
    category: "Web",
    description: "Typed JavaScript for scalable apps and services.",
    extension: "ts",
    monacoLanguage: "typescript",
    runnable: true,
    runtime: "typescript",
    runtimeLabel: "TypeScript runtime",
    version: "*",
    template: 'const greeting: string = "Welcome to VoidLAB";\nconsole.log(greeting);\n',
  },
  {
    id: "python",
    label: "Python",
    category: "General",
    description: "Readable, versatile, and ideal for automation or ML.",
    extension: "py",
    monacoLanguage: "python",
    runnable: true,
    runtime: "python",
    runtimeLabel: "Python runtime",
    version: "*",
    template: 'print("Welcome to VoidLAB")\n',
  },
  {
    id: "java",
    label: "Java",
    category: "Enterprise",
    description: "Strongly typed language for large backend systems.",
    extension: "java",
    monacoLanguage: "java",
    runnable: true,
    runtime: "java",
    runtimeLabel: "JVM runtime",
    version: "*",
    template:
      'class Main {\n  public static void main(String[] args) {\n    System.out.println("Welcome to VoidLAB");\n  }\n}\n',
  },
  {
    id: "c",
    label: "C",
    category: "Systems",
    description: "Classic systems programming language.",
    extension: "c",
    monacoLanguage: "c",
    runnable: true,
    runtime: "c",
    runtimeLabel: "Native compiler",
    version: "*",
    template:
      '#include <stdio.h>\n\nint main() {\n  printf("Welcome to VoidLAB\\n");\n  return 0;\n}\n',
  },
  {
    id: "cpp",
    label: "C++",
    category: "Systems",
    description: "High-performance language for large applications.",
    extension: "cpp",
    monacoLanguage: "cpp",
    runnable: true,
    runtime: "cpp",
    runtimeLabel: "Native compiler",
    version: "*",
    template:
      '#include <iostream>\n\nint main() {\n  std::cout << "Welcome to VoidLAB" << std::endl;\n}\n',
  },
  {
    id: "go",
    label: "Go",
    category: "Backend",
    description: "Simple and efficient language for cloud services.",
    extension: "go",
    monacoLanguage: "go",
    runnable: true,
    runtime: "go",
    runtimeLabel: "Go runtime",
    version: "*",
    template:
      'package main\n\nimport "fmt"\n\nfunc main() {\n  fmt.Println("Welcome to VoidLAB")\n}\n',
  },
  {
    id: "rust",
    label: "Rust",
    category: "Systems",
    description: "Memory-safe systems programming with strong performance.",
    extension: "rs",
    monacoLanguage: "rust",
    runnable: true,
    runtime: "rust",
    runtimeLabel: "Rust toolchain",
    version: "*",
    template: 'fn main() {\n    println!("Welcome to VoidLAB");\n}\n',
  },
  {
    id: "php",
    label: "PHP",
    category: "Web",
    description: "Server-side scripting for dynamic web apps.",
    extension: "php",
    monacoLanguage: "php",
    runnable: true,
    runtime: "php",
    runtimeLabel: "PHP runtime",
    version: "*",
    template: '<?php\necho "Welcome to VoidLAB";\n',
  },
  {
    id: "ruby",
    label: "Ruby",
    category: "Web",
    description: "Expressive language for productive app development.",
    extension: "rb",
    monacoLanguage: "ruby",
    runnable: true,
    runtime: "ruby",
    runtimeLabel: "Ruby runtime",
    version: "*",
    template: 'puts "Welcome to VoidLAB"\n',
  },
  {
    id: "swift",
    label: "Swift",
    category: "Mobile",
    description: "Modern Apple-platform language with clean syntax.",
    extension: "swift",
    monacoLanguage: "swift",
    runnable: true,
    runtime: "swift",
    runtimeLabel: "Swift runtime",
    version: "*",
    template: 'print("Welcome to VoidLAB")\n',
  },
  {
    id: "kotlin",
    label: "Kotlin",
    category: "Mobile",
    description: "Concise JVM language used across Android and backend.",
    extension: "kt",
    monacoLanguage: "kotlin",
    runnable: true,
    runtime: "kotlin",
    runtimeLabel: "Kotlin runtime",
    version: "*",
    template: 'fun main() {\n  println("Welcome to VoidLAB")\n}\n',
  },
  {
    id: "bash",
    label: "Bash",
    category: "Scripting",
    description: "Shell scripting for automation and operations.",
    extension: "sh",
    monacoLanguage: "shell",
    runnable: true,
    runtime: "bash",
    runtimeLabel: "Shell runtime",
    version: "*",
    template: 'echo "Welcome to VoidLAB"\n',
  },
  {
    id: "powershell",
    label: "PowerShell",
    category: "Scripting",
    description: "Task automation language for modern ops workflows.",
    extension: "ps1",
    monacoLanguage: "powershell",
    runnable: true,
    runtime: "powershell",
    runtimeLabel: "PowerShell runtime",
    version: "*",
    template: 'Write-Output "Welcome to VoidLAB"\n',
  },
  {
    id: "lua",
    label: "Lua",
    category: "Embedded",
    description: "Lightweight language used in games and embedded apps.",
    extension: "lua",
    monacoLanguage: "lua",
    runnable: true,
    runtime: "lua",
    runtimeLabel: "Lua runtime",
    version: "*",
    template: 'print("Welcome to VoidLAB")\n',
  },
];

const editorOnlyLanguages: LanguageOption[] = [
  {
    id: "html",
    label: "HTML",
    category: "Markup",
    description: "Markup for page structure.",
    extension: "html",
    monacoLanguage: "html",
    runnable: false,
    template: "<section>\n  <h1>Welcome to VoidLAB</h1>\n</section>\n",
  },
  {
    id: "css",
    label: "CSS",
    category: "Markup",
    description: "Styling language for web interfaces.",
    extension: "css",
    monacoLanguage: "css",
    runnable: false,
    template: "body {\n  background: #030712;\n  color: white;\n}\n",
  },
  {
    id: "json",
    label: "JSON",
    category: "Data",
    description: "Structured data format.",
    extension: "json",
    monacoLanguage: "json",
    runnable: false,
    template: '{\n  "product": "VoidLAB",\n  "status": "ready"\n}\n',
  },
  {
    id: "markdown",
    label: "Markdown",
    category: "Docs",
    description: "Documentation-friendly lightweight markup.",
    extension: "md",
    monacoLanguage: "markdown",
    runnable: false,
    template: "# VoidLAB\n\nBuild, run, and ship from the cloud.\n",
  },
  {
    id: "yaml",
    label: "YAML",
    category: "Data",
    description: "Readable config format for pipelines and apps.",
    extension: "yml",
    monacoLanguage: "yaml",
    runnable: false,
    template: "name: voidlab\nstatus: ready\n",
  },
  {
    id: "sql",
    label: "SQL",
    category: "Data",
    description: "Query language for relational databases.",
    extension: "sql",
    monacoLanguage: "sql",
    runnable: false,
    template: "select 'Welcome to VoidLAB' as message;\n",
  },
  {
    id: "xml",
    label: "XML",
    category: "Markup",
    description: "Structured markup for document-style data.",
    extension: "xml",
    monacoLanguage: "xml",
    runnable: false,
    template: "<message>Welcome to VoidLAB</message>\n",
  },
];

export const languageGroups = [
  { label: "Runnable languages", items: runnableLanguages },
  { label: "Editor-only formats", items: editorOnlyLanguages },
];

export const allLanguages = [...runnableLanguages, ...editorOnlyLanguages];
export const DEFAULT_LANGUAGE = runnableLanguages[0];

export const getLanguageById = (id: string) =>
  allLanguages.find((item) => item.id === id) ?? DEFAULT_LANGUAGE;
